/* ==========================================================================
   Book configuration.
   Page assets and pageCount are regenerated by tools/build_ebook.py — it
   rewrites ../files/book.json. Everything below is hand-editable.
   ========================================================================== */
var bookConfig = {
  /* shown in the title bar, the tab and social previews */
  title: "한성대학교 AI 바이브코딩 기초·심화 프로그램",

  /* where the generated page manifest lives, relative to mobile/index.html */
  manifest: "../files/book.json",

  /* asset folders, relative to mobile/index.html */
  pagePath:  "../files/mobile/",
  thumbPath: "../files/thumb/",

  /* two-page spread once the viewport is at least this wide (px) and landscape */
  spreadMinWidth: 900,

  /* page 1 is treated as a standalone cover in spread mode */
  coverAlone: true,

  /* seconds between pages while auto-play is running */
  autoPlayDuration: 5,

  /* optional original file offered under the download button ("" hides it) */
  downloadURL: "",

  /* right-to-left reading order (for Arabic/Hebrew style books) */
  rightToLeft: false
};
